ALTER TABLE animal ADD COLUMN IF NOT EXISTS caminho_foto VARCHAR(500);
ALTER TABLE animal ADD COLUMN IF NOT EXISTS cor VARCHAR(50);
ALTER TABLE animal ADD COLUMN IF NOT EXISTS descricao TEXT;
ALTER TABLE animal ADD COLUMN IF NOT EXISTS responsavel VARCHAR(100);